import PDFDocument from 'pdfkit';
import fs from 'fs';
import { US_MAINTENANCE_DATA } from './shared/location-maintenance-data.js';

const MONTH_NAMES = [
  'January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December'
];

function generateMaintenancePDF() {
  const doc = new PDFDocument({ size: 'LETTER', margin: 50 });
  const outputPath = 'home-maintenance-tasks.pdf';
  
  doc.pipe(fs.createWriteStream(outputPath));

  // Title Page
  doc.fontSize(24).font('Helvetica-Bold').text('Home Maintenance Tasks', { align: 'center' });
  doc.moveDown();
  doc.fontSize(16).font('Helvetica').text('Organized by Climate Zone and Month', { align: 'center' });
  doc.moveDown(2);
  doc.fontSize(10).font('Helvetica-Oblique').text('Generated: ' + new Date().toLocaleDateString(), { align: 'center' });
  doc.moveDown(3);

  // Sort regions by climate zone
  const regions = Object.values(US_MAINTENANCE_DATA).sort((a, b) => 
    a.climateZone.localeCompare(b.climateZone)
  );

  // Process each region
  regions.forEach((regionData, regionIndex) => {
    if (regionIndex > 0) {
      doc.addPage();
    }

    // Region Header
    doc.fontSize(20).font('Helvetica-Bold').fillColor('#1560a2')
      .text(`${regionData.region}`, { continued: false });
    doc.fontSize(12).font('Helvetica-Oblique').fillColor('#666666')
      .text(`Climate Zone: ${regionData.climateZone}`);
    doc.moveDown(1.5);

    // Process each month
    for (let month = 1; month <= 12; month++) {
      const monthData = regionData.monthlyTasks[month];
      if (!monthData) continue;

      // Check if we need a new page
      if (doc.y > 650) {
        doc.addPage();
      }

      // Month Header
      doc.fontSize(14).font('Helvetica-Bold').fillColor('#2c0f5b')
        .text(`${MONTH_NAMES[month - 1]} - Priority: ${monthData.priority.toUpperCase()}`);
      doc.moveDown(0.5);

      // Seasonal Tasks
      if (monthData.seasonal && monthData.seasonal.length > 0) {
        doc.fontSize(11).font('Helvetica-Bold').fillColor('#000000')
          .text('Seasonal Tasks:');
        doc.fontSize(10).font('Helvetica').fillColor('#333333');
        
        monthData.seasonal.forEach((task, index) => {
          const bullet = `  • ${task}`;
          doc.text(bullet, { indent: 10 });
        });
        doc.moveDown(0.5);
      }

      // Weather-Specific Tasks
      if (monthData.weatherSpecific && monthData.weatherSpecific.length > 0) {
        doc.fontSize(11).font('Helvetica-Bold').fillColor('#000000')
          .text('Weather-Specific Tasks:');
        doc.fontSize(10).font('Helvetica').fillColor('#333333');
        
        monthData.weatherSpecific.forEach((task, index) => {
          const bullet = `  • ${task}`;
          doc.text(bullet, { indent: 10 });
        });
        doc.moveDown(0.5);
      }

      doc.moveDown(0.5);
    }

    // Year-Round Tasks
    doc.addPage();
    doc.fontSize(16).font('Helvetica-Bold').fillColor('#1560a2')
      .text(`${regionData.region} - Year-Round Tasks`);
    doc.moveDown(1);
    
    if (regionData.yearRoundTasks && regionData.yearRoundTasks.length > 0) {
      doc.fontSize(10).font('Helvetica').fillColor('#333333');
      regionData.yearRoundTasks.forEach((task) => {
        doc.text(`  • ${task}`, { indent: 10 });
      });
      doc.moveDown(1.5);
    }

    // Special Considerations
    if (regionData.specialConsiderations && regionData.specialConsiderations.length > 0) {
      doc.fontSize(16).font('Helvetica-Bold').fillColor('#1560a2')
        .text(`${regionData.region} - Special Considerations`);
      doc.moveDown(1);
      doc.fontSize(10).font('Helvetica').fillColor('#333333');
      regionData.specialConsiderations.forEach((consideration) => {
        doc.text(`  • ${consideration}`, { indent: 10 });
      });
    }
  });

  // Footer on last page
  doc.moveDown(2);
  doc.fontSize(8).font('Helvetica-Oblique').fillColor('#999999')
    .text('Generated by HomeBase - Your Home Maintenance Companion', { align: 'center' });

  doc.end();

  console.log(`✅ PDF generated successfully: ${outputPath}`);
  console.log(`📄 Total regions included: ${regions.length}`);
  console.log(`📍 Regions: ${regions.map(r => r.region).join(', ')}`);
}

// Run the generator
try {
  generateMaintenancePDF();
} catch (error) {
  console.error('❌ Error generating PDF:', error);
  process.exit(1);
}
